nodeLinker: node-modules

plugins:
  - checksum: e8cb44d20cf985029eb0e642391fecc4a123184522f0facc391ef2a6e65d27ad531990fc9d2428a10c7aa2627e5edbb3d7628dbdb2b01cdc4b7e105c1515bdba
    path: .yarn/plugins/@yarnpkg/plugin-preset.cjs
    spec: "https://github.com/newhighsco/yarn/releases/download/%40newhighsco%2Fyarn-plugin-preset%401.1.1/plugin-preset.js"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
