export const BUTTON = 'Button'
export const CARD = 'Card'
export const CONTENT_CONTAINER = 'ContentContainer'
export const CREDIT_LOCKUP = 'CreditLockup'
export const ICON = 'Icon'
export const GRID = 'Grid'
export const PAGE_CONTAINER = 'PageContainer'
export const SITE_CONTAINER = 'SiteContainer'
